### ISSUE TITLE
Oops! Invalid binary or the file doesn't exists.

### ISSUE THREAD

**Issue by victorwbuzz** [rafajaques/php-assistant#115]
This is happening when trying to point php bin using dialog browser or type method.

OS: Windows 10 x64 Pro
PHP-Assistant: x32 and x64
PHP bin: 5.6.16 and 7.0.0 (both x32)

![image](https://cloud.githubusercontent.com/assets/9410768/16125114/7aedef50-33c8-11e6-9f87-c2c3621d64ef.png)

**Comment by rafajaques** [comment]
Please, send output of
`C:\path\to\php.exe --version`

**Comment by victorwbuzz** [comment]
PHP 5.6.16 (cli) (built: Nov 25 2015 18:52:34)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by rafajaques** [comment]
Well, this is the expected.
Do you have NodeJS? Maybe running in debug mode should tell us what is happening.
I'm trying to get a Windows 10 VM to reproduce the error.

**Comment by victorwbuzz** [comment]
Yes, i have.

**Comment by victorwbuzz** [comment]
![image](https://cloud.githubusercontent.com/assets/9410768/16130391/2f7285c4-33df-11e6-9641-8316584c6681.png)
![image](https://cloud.githubusercontent.com/assets/9410768/16130399/36220192-33df-11e6-90e0-c6d245613281.png)

**Comment by rafajaques** [comment]
I just ran Assistant in Windows 10 x64 with PHP version from XAMPP.
What are the paths to your PHP binaries?
Maybe it's a permission or white spaces problem.

**Comment by victorwbuzz** [comment]
C:\laragon\bin\php\php-5.6.16\php.exe

**Comment by victorwbuzz** [comment]
Just an obs: I am running other php tools and sulime extensions with that php bin.

**Comment by victorwbuzz** [comment]
I guess it's not about path. Tried in C:\php\php.exe same problem. Ran with admin perm, nope too =/

**Comment by rafajaques** [comment]
I'll have to add some debug functionality, then.
Going to do some tests here and will let you know as soon as possible.

**Comment by victorwbuzz** [comment]
php 5.5.12 fails too

**Comment by victorwbuzz** [comment]
No effect =/
![image](https://cloud.githubusercontent.com/assets/9410768/16131236/a3d29554-33e3-11e6-8ca7-7cf16b283530.png)

**Comment by victorwbuzz** [comment]
yay
![image](https://cloud.githubusercontent.com/assets/9410768/16131266/cba8ddf4-33e3-11e6-94e7-cc737a9b9770.png)

![image](https://cloud.githubusercontent.com/assets/9410768/16131260/c4e559a2-33e3-11e6-811e-1e9ef1181483.png)

**Comment by victorwbuzz** [comment]
It's only the very first one. Other php version (not php 7) will be added in Settings.
![image](https://cloud.githubusercontent.com/assets/9410768/16131322/0b2c13b0-33e4-11e6-9e84-52c9db38cf64.png)

**Comment by rafajaques** [comment]
Very good. I'll try to use the same paths to reproduce the error.

**Comment by rafajaques** [comment]
I couldn't reproduce the error.
May you send me the result of `C:\laragon\bin\php\php-7.0.0\php.exe --version`?

**Comment by rafajaques** [comment]
I've made a few modifications in source code.
Please, clone again and try adding the non working php version.

**Comment by victorwbuzz** [comment]
Now the browser dialog accepts php 5.6.16 but 7.0.0 not.

The output of php 7 bin --version

```
PHP 7.0.0 (cli) (built: Dec  3 2015 11:36:59) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by rafajaques** [comment]
With new bundled version, that shouldn't be a problem anymore.
