### ISSUE TITLE
Fix list spacing OR printing HTML elements

### ISSUE THREAD

**Issue by germanocorrea** [rafajaques/php-assistant#12]
When printing lists, there's too much space between list itens. This is caused by "white-space: pre;" from the id "console", index.css.

See last print screen, with "white-space" disabled.

![captura de tela de 2016-02-15 08-25-32](https://cloud.githubusercontent.com/assets/9283794/13046062/d5860dfa-d3bd-11e5-90c8-c793fe557db2.png)
![captura de tela de 2016-02-15 08-29-58](https://cloud.githubusercontent.com/assets/9283794/13046149/5cf88538-d3be-11e5-83e0-ffb127693369.png)
![captura de tela de 2016-02-15 08-30-13](https://cloud.githubusercontent.com/assets/9283794/13046164/6a9175ec-d3be-11e5-95f5-f68ae6942101.png)

**Comment by germanocorrea** [comment]
The problem here is that if you disable "white-space: pre;", things like PHP_EOL doesn't work anymore.
If you mean to simulate a terminal, transform strings printed like ">" into html entities should do the trick, so things such as this list doesn't work anymore, and then it's working like a terminal.

And I'm writing everything in english to preserve your choice of opening every issue in english :v

**Comment by rafajaques** [comment]
The output should be in "terminal-like" appearance.
I guess a good option is to add a "Show as HTML" option.

**Comment by germanocorrea** [comment]
Indeed it is. In terminal-like appearance, like I said, transform strings into html entities to avoid printing something like lists. Then, the "show as HTML" don't use "white-space:pre;", avoiding space between list itens, among other things.

**Comment by rafajaques** [comment]
Solved.
