### ISSUE TITLE
Create pt-BR README

### ISSUE THREAD

**Issue by rafajaques** [rafajaques/php-assistant#122]

**Comment by viniciusss** [comment]
Tenho interesse em ajudar, está pensando em apenas uma versão traduzida? Ou tem algo a mais em mente?

**Comment by rafajaques** [comment]
Na verdade não. Pensei em só fazer um arquivo chamado README-pt_BR.md com o mesmo conteúdo do README.md, mas traduzido.

**Comment by luizfpq** [comment]
Posso colaborar revisando a tradução, tenho vasta experiência.
Em 23 de jun de 2016 8:29 AM, "Rafael Jaques" <notifications@github.com>
escreveu:

**Comment by rafajaques** [comment]
Fiquem a vontade. Só cuidem para não fazer a mesma coisa.
Podem fazer um fork, criar um novo arquivo chamado `README-pt_BR.md` e traduzir o texto do original.
Depois mandem um pull request que eu aceito.
