### ISSUE TITLE
Unnecessary packages?

### ISSUE THREAD

**Issue by marcelaraujo** [rafajaques/php-assistant#123]
These pakcages _eslint-plugin-jsx-a11y_ and _eslint-plugin-react_ are necessary?

You are not using React so this is confuse.

Thanks Rafa

**Comment by rafajaques** [comment]
It was not set by me.
I admit that I don't know eslint very much, so I really don't know if there are any unnecessary package.

If you're sure about that, I'll remove them.

**Comment by marcelaraujo** [comment]
Let me check that @rafajaques ;)

**Comment by rafajaques** [comment]
I verified and that's not possible. We use AIRBNB rules for linting.

`npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-react@^5.0.1 but none was installed.`

Unfortunately we can do nothing. I'm closing the issue.
Thanks!
