### ISSUE TITLE
Update Ace linter 

### ISSUE THREAD

**Issue by rafajaques** [rafajaques/php-assistant#126]
This issue is related to #116.
The editor used in PHP Assistant is [Ace Editor](https://ace.c9.io/).
PHP linter, that looks for syntax errors, is not recognizing some of new PHP features.
I think updating PHP linter should solve the problem, but as far as I know, there is no update, so it will probably lead to a modification in Ace linter itself.

**Comment by kartik95** [comment]
What exactly do we need to do here? @rafajaques

**Comment by rafajaques** [comment]
@kartik95 Updated issue description.

**Comment by kartik95** [comment]
I am new to Ace Editor. Can you give me some directions? @rafajaques

**Comment by rafajaques** [comment]
I found some interesting issue here: https://github.com/ajaxorg/ace/issues/2908.

**Comment by fernandobandeira** [comment]
Seems like the PR ajaxorg/ace#3107 will solve this issue, the fixes are on [https://github.com/nikic/ace/tree/php7](https://github.com/nikic/ace/tree/php7). Theres a gist with the full file: https://gist.github.com/nikic/91ee0bc7ac74659366a8ae90b8f2d15e

**Comment by rafajaques** [comment]
> Also note that all the new 7.0 features shouldn't work, for example the new tokens:
@fernandobandeira Maybe, but AFAIK, it's working.
If you take a look at [https://3v4l.org](https://3v4l.org) you'll see that it's working.

**Comment by fernandobandeira** [comment]
If you check that PR you'll see that the creator of this online php shell (Sjon) is one of the ppl that are testing and he stated that he manually applied the fix. So thats why its probably working however if you check the bare editor online: https://ace.c9.io/build/kitchen-sink.html you'll see that it's not working.

**Comment by rafajaques** [comment]
Yes. But I brought that for the sake of clarification.
He told that it was possible to rebuild the parser, but I don't have time to figure out how to do that right now...

**Comment by SjonHortensius** [comment]
Here's what I did:

* clone https://github.com/nikic/ace, checkout php7 branch
* edit lib/ace/mode/php/php.js; replace the PHP.Lexer part (~ 990 lines) with the [patch from nikita](https://gist.github.com/nikic/91ee0bc7ac74659366a8ae90b8f2d15e)
* run `node ./Makefile.dryice.js -m` to build a file suitable for release

**Comment by rafajaques** [comment]
@SjonHortensius I'll do that! Thank you very much!

**Comment by rafajaques** [comment]
@SjonHortensius Worked perfect, but I used the full file from nikic PR https://github.com/ajaxorg/ace/pull/3107.
Thanks! I'll be closing this issue soon.
