### ISSUE TITLE
Remove menubar from welcome screen

### ISSUE THREAD

**Issue by rafajaques** [rafajaques/php-assistant#141]
Disable menubar in welcome screen.
Keep only "PHP Assistant" and "File" menus.
"File" will have only "Exit" option.

**Comment by knox97** [comment]
hey can I work on this one?

**Comment by rafajaques** [comment]
Sure. Feel free to get your hands on.
First you need to fork it, then clone to your computer, update the files and commit then back to GitHub. When your files are online, you send a pull request.

**Comment by rafajaques** [comment]
If you're not familiar with Git and use Windows or Mac, you may try [GitHub Desktop](https://desktop.github.com/).

**Comment by flyingace** [comment]
#145 should take care of this. I'm assuming you only wanted to hide the language selection bar temporarily so the changes made should be easy to reverse.

**Comment by rafajaques** [comment]
@flyingace Well, that's not exactly what I meant.
There is a menu bar in OSX that is always present. 
So it's more a OSX issue.

**Comment by flyingace** [comment]
@rafajaques Could you add a screenshot of the menubar so I'm clearer about what you want removed?
