### ISSUE TITLE
Auto run while editing

### ISSUE THREAD

**Issue by giovannipds** [rafajaques/php-assistant#33]
Hey!

I think that one feature that would be great, it would be the possibility to auto run after the user types. You can check the `onkeyup` event and sets a timeout, like 1 or 2 seconds to run that exec function.

;)

**Comment by rafajaques** [comment]
This may be a problem when you're typing and make a mistake or is trying to fix an infinite loop.
A shortcut to Run should fix the problem.

**Comment by giovannipds** [comment]
A shortcut to exec will be great too, but I think an autorun will be even greater. In my opinion, is essential. Almost every app / IDE have something like it...

About mistakes, well, mistakes happen. We could check how long the script takes to to be executed and prompt an alert while stopping the script. That would fix errors that may occur while we try to fix infinite loops or something like it.

I can try to help you on this feature if you want. Maybe it'd be cool to enjoy how Elecron actually works. What you think? Can I?

See ya!

**Comment by rafajaques** [comment]
Auto run after every single character can be a problem.
An auto run after a few seconds or after a set of characters (like ';' or '}') should do the trick.
What do you think?

**Comment by giovannipds** [comment]
Hm... if we would base it at characters like ";", or "}", we won't be able to run it after a normal editing, like a single letter in the middle of a sentence, or something like that.

In which means do you think it will be a problem?

Can't we do something like [CodePen](http://codepen.io/pen/)? - They seem to be running after 1s, just after the user stops typing. I was thinking this would be our way.

Here's and example of implementation: http://codepen.io/giovannipds/pen/pyZdKb

What you think?

**Comment by rafajaques** [comment]
The problem is not the implementation itself, but the tons of errors and warnings generated as you type.

> Ah, another thing, we can also listen to the Enter key and running it right away. Or as a shortcut, like Cmd/Ctrl + Enter.

It's already implemented (#3).

**Comment by giovannipds** [comment]
Hm, and the errors and warnings would be a trouble somehow? Will it need something like a PHP lint, before running your current code?

If the errors and warnings would just be shown, I do not see any problem on it... I guess this is the right way, it should be always shown.

Well, I don't know how could I help you more... if there's something I can do, just let me know.

Good that the shortcut is already implemented. :smiley:

**Comment by rafajaques** [comment]
You gave me an idea. 
If we make auto run based on Ace [syntax validation](https://github.com/ajaxorg/ace/wiki/Syntax-validation) (that runs every time the user stops typing), I think we can balance between a bunch of errors and a lifeless auto run.

**Comment by giovannipds** [comment]
Sounds like a reasonable idea, it may work well.

I didn't know Ace yet, it looks like a great project.

**Comment by rafajaques** [comment]
It's the editor used in the project. It's a nice project, indeed.

**Comment by rafajaques** [comment]
Done.

**Comment by giovannipds** [comment]
Niice! Congrats. Gonna check it asap. ;)

**Comment by rafajaques** [comment]
So far it's not present in any release, just in the master branch. I'm gonna fix that soon.

**Comment by giovannipds** [comment]
:+1: I'll wait that. =)
