### ISSUE TITLE
Switch from Bootstrap to Materialize

### ISSUE THREAD

**Issue by rafajaques** [rafajaques/php-assistant#45]
Material Design seems to have better tools.
[Materialize](http://materializecss.com/) is a CSS framework that implements Google's Material Design.

**Comment by Johann-S** [comment]
Materialize is still in Alpha and less stable than Bootstrap in my opinion

**Comment by rafajaques** [comment]
Yes. I'll probably abandon this idea. A friend told me that Materialize JS can be weird sometimes...

**Comment by Johann-S** [comment]
If you want to have a material theme you can use Bootswatch Paper : https://bootswatch.com/paper/

**Comment by rafajaques** [comment]
I'll keep an eye on that! Thanks!
