### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Johann-S** [rafajaques/php-assistant#51]
Sorry to ask but how can I build my own release of php-assistant with Electron ?

Plus, I think it would be interesting to add it to the ``README.md`` for contributors

**Comment by rafajaques** [comment]
That's a very good question! Since that was a solo project, I didn't take a time to write it.
Going to do it right now!

**Comment by rafajaques** [comment]
It's done.
Thank you for the tip!

**Comment by Johann-S** [comment]
Thank you :+1:
