### ISSUE TITLE
Cannot run npm run dev

### ISSUE THREAD

**Issue by Johann-S** [rafajaques/php-assistant#63]
Hi,

I cannot run this command ``npm run dev``
this is the error I got from my cmd : 
![error](https://cloud.githubusercontent.com/assets/1689750/15315394/a0e59014-1c17-11e6-8ed5-708f311a4f8a.jpg)

**Comment by rafajaques** [comment]
Does `npm start` works?
It seems to be something related to Windows. I don't have any Windows machine right now, but I will try to get one as soon as possible.

**Comment by Johann-S** [comment]
No ``npm start`` doesn't work

**Comment by rafajaques** [comment]
I had an issue while starting on Windows.
It's not the same, but I solved installing [Visual C++ Redistributable for VS 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145).
Do you have that package installed?

**Comment by Johann-S** [comment]
Yes I installed this package now but it still doesn't work

**Comment by rafajaques** [comment]
Did you update your branch to the latest version?

**Comment by rafajaques** [comment]
I juste remembered of something: with the launch of Electron 1.0, a lot of things have changed in the application.
Make sure you have the most recent files, from the main branch, not the fork one (or [sync your fork](https://help.github.com/articles/syncing-a-fork/#platform-windows)).

**Comment by Johann-S** [comment]
Yes my fork is up to date.

Finally I installed ``electron-prebuilt`` package globally with ``npm i -g electron-prebuilt`` and it works

**Comment by rafajaques** [comment]
That's strange. But I'm happy to know that it's working now.
