### ISSUE TITLE
Add tips to sidebar in presentation mode

### ISSUE THREAD

**Issue by rafajaques** [rafajaques/php-assistant#66]
[qTip2](http://qtip2.com/) is a good choice.

**Comment by Johann-S** [comment]
Why do you want to use qTip2 instead of Bootstrap tooltips ?

**Comment by rafajaques** [comment]
That's new to me! I'm not very familiar with bootstrap.
I'll take a look! Thanks.

**Comment by Johann-S** [comment]
See the doc : http://getbootstrap.com/javascript/#tooltips

Maybe Bootstrap tooltips are less customisable than qTip2

**Comment by rafajaques** [comment]
It seems Bootstrap tooltips will fit just fine. That's exactly what I needed.
