### ISSUE TITLE
JavaScript style guide

### ISSUE THREAD

**Issue by Johann-S** [rafajaques/php-assistant#70]
Maybe for the futur of this project it will be interesting to have a JavaScript code style like this : 
https://github.com/airbnb/javascript

**Comment by rafajaques** [comment]
That's a good tip, because this is my first use of Electron. 
Code is full of trash and need a refactor.
I'm gonna read the style guide.
Thanks.

**Comment by Johann-S** [comment]
You can use ESlint to check the entire JavaScript in PHP-Assistant and you can select the airbnb preset. See those links : 

https://eslint.org/
https://github.com/airbnb/javascript/blob/master/linters/.eslintrc

If you're interested about that, I can work on it

**Comment by rafajaques** [comment]
If you have the time to, I'd be very grateful!

**Comment by Johann-S** [comment]
Yes sure :+1: 

The next step is to enable Travis to check JavaScript for PRs
