### ISSUE TITLE
Any way to workaround no-unused-vars?

### ISSUE THREAD

**Issue by rafajaques** [rafajaques/php-assistant#77]
@Johann-S 
I'm have some issues with functions like **checkPresentation()** that are not called in the same file but are called in others.
It returns a **no-unused-vars** error on Lint.
I used /* eslint-disable no-unused-vars */. Any better way to accomplish that?

**Comment by rafajaques** [comment]
Fixed.

**Comment by Johann-S** [comment]
I don't know how to fix this instead of using `` eslint-disable no-unused-vars ``.

How did you fixed this ?

**Comment by rafajaques** [comment]
I disabled it globally. Maybe in the future we can find another way to fix that.
I read something about "exported" variables, but it does not work when the environment is node or commonjs.
